### ISSUE TITLE
Running into errors while loading szurulink

### ISSUE THREAD

**Issue by ninjazan420** [robobenklein/unhexium-cogs#4]
hey there,

maybe you could help me get this running. probably it's dockers fault, but im not sure
i'm using [this package ](https://github.com/PhasecoreX/docker-red-discordbot) to get cog running and every external or internal package runs fine, except for szurulink :)

after using the `load szurulink` command:

<details>[2024-05-26 19:56:00] [ERROR] red.downloader: Invalid JSON information file at path: /data/cogs/RepoManager/repos/unhexium-cogs/utk_netid_auth/info.json Error: Expecting property name enclosed in double quotes: line 11 column 1 (char 381) [2024-05-26 19:56:22] [ERROR] red: Package loading failed Traceback (most recent call last): File "/data/venv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 189, in _load await bot.load_extension(spec) File "/data/venv/lib/python3.11/site-packages/redbot/core/bot.py", line 1680, in load_extension lib = spec.loader.load_module() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 605, in _check_name_wrapper File "", line 1120, in load_module File "", line 945, in load_module File "", line 290, in _load_module_shim File "", line 721, in _load File "", line 690, in _load_unlocked File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "/data/cogs/CogManager/cogs/szurulink/__init__.py", line 2, in from .szurulink import SzuruPoster File "/data/cogs/CogManager/cogs/szurulink/szurulink.py", line 20, in from async_timeout import timeout ModuleNotFoundError: No module named 'async_timeout' [2024-05-26 19:57:42] [ERROR] red: Package loading failed Traceback (most recent call last): File "/data/venv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 189, in _load await bot.load_extension(spec) File "/data/venv/lib/python3.11/site-packages/redbot/core/bot.py", line 1680, in load_extension lib = spec.loader.load_module() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 605, in _check_name_wrapper File "", line 1120, in load_module File "", line 945, in load_module File "", line 290, in _load_module_shim File "", line 721, in _load File "", line 690, in _load_unlocked File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "/data/cogs/CogManager/cogs/szurulink/__init__.py", line 2, in from .szurulink import SzuruPoster File "/data/cogs/CogManager/cogs/szurulink/szurulink.py", line 20, in from async_timeout import timeout ModuleNotFoundError: No module named 'async_timeout' [2024-05-26 20:02:21] [ERROR] red: Package loading failed Traceback (most recent call last): File "/data/venv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 189, in _load await bot.load_extension(spec) File "/data/venv/lib/python3.11/site-packages/redbot/core/bot.py", line 1680, in load_extension lib = spec.loader.load_module() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 605, in _check_name_wrapper File "", line 1120, in load_module File "", line 945, in load_module File "", line 290, in _load_module_shim File "", line 721, in _load File "", line 690, in _load_unlocked File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "/data/cogs/CogManager/cogs/szurulink/__init__.py", line 2, in from .szurulink import SzuruPoster File "/data/cogs/CogManager/cogs/szurulink/szurulink.py", line 20, in from async_timeout import timeout ModuleNotFoundError: No module named 'async_timeout' [2024-05-26 20:07:37] [ERROR] red: Package loading failed Traceback (most recent call last): File "/data/venv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 189, in _load await bot.load_extension(spec) File "/data/venv/lib/python3.11/site-packages/redbot/core/bot.py", line 1680, in load_extension lib = spec.loader.load_module() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 605, in _check_name_wrapper File "", line 1120, in load_module File "", line 945, in load_module File "", line 290, in _load_module_shim File "", line 721, in _load File "", line 690, in _load_unlocked File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "/data/cogs/CogManager/cogs/szurulink/__init__.py", line 2, in from .szurulink import SzuruPoster File "/data/cogs/CogManager/cogs/szurulink/szurulink.py", line 20, in from async_timeout import timeout ModuleNotFoundError: No module named 'async_timeout' [2024-05-26 20:12:34] [ERROR] red: Package loading failed Traceback (most recent call last): File "/data/venv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 189, in _load await bot.load_extension(spec) File "/data/venv/lib/python3.11/site-packages/redbot/core/bot.py", line 1680, in load_extension lib = spec.loader.load_module() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 605, in _check_name_wrapper File "", line 1120, in load_module File "", line 945, in load_module File "", line 290, in _load_module_shim File "", line 721, in _load File "", line 690, in _load_unlocked File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "/data/cogs/CogManager/cogs/szurulink/__init__.py", line 2, in from .szurulink import SzuruPoster File "/data/cogs/CogManager/cogs/szurulink/szurulink.py", line 20, in from async_timeout import timeout ModuleNotFoundError: No module named 'async_timeout' 
</details>

greetings and thanks for your help!

**Comment by ninjazan420** [comment]
Fixed it by usying `prefix.pipinstall async_timeout` :)
Have a grerat one!

**Comment by robobenklein** [comment]
Do I perhaps need to add that dependency to the info.json?

**Comment by ninjazan420** [comment]
> Do I perhaps need to add that dependency to the info.json?

I guess. It got seperated as a [standalone pip](https://pypi.org/project/async-timeout/) right after your latest push in 2023 😋
